import java.io.File;
import java.io.IOException;
import java.util.List;

import org.apache.lucene.queryparser.classic.QueryParser;

import extras.Constants;
import extras.FileHandling;
import tasks.Task1;
import tasks.Task2;

/**
 * Entry class to run all the tasks in the assignment
 * @author takkyon
 *
 */
public class Program {

	private Task1 task1;
	private Task2 task2;
	private FileHandling fileHandling;
	
	/**
	 * Default Constructor
	 * @throws IOException
	 */
	public Program() throws IOException {
		this.fileHandling = new FileHandling();
		this.setupQueries();
		this.task1 = Task1.newInstance();
		// this.task2 = Task2.newInstance();
	}
	
	/**
	 * Runs all the tasks, and
	 * then prints result files
	 */
	public void run() {
		this.task1.run();
		// this.task2.run();
		this.printFiles();
	}
	
	private void setupQueries() {
		try {
			List<String> queries = this.fileHandling.getLines(new File(Constants.QUERY_FILE));
			Constants.queries = new String[queries.size()];
			Constants.queryFileNames = new String[queries.size()];
			for(int i = 0; i<queries.size();++i) {
				Constants.queries[i] = QueryParser.escape(queries.get(i));
						//queries.get(i).replaceAll("[^a-zA-Z0-9_ ]", " ");
				Constants.queryFileNames[i] = "Q" + i;
			}
		}catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Print all the file details
	 */
	private void printFiles() {
		System.out.println("\n\n-- The task has been successfully completed..All the files are located under files/task/1..");
		System.out.println("\n-- Files generated by Lucene to index are located under files/index..");
		System.out.println("\n-- All raw documents used are located under files/corpus..");
	}
	
	/**
	 * Entry point for the class
	 * @param args
	 */
	public static void main(String[] args) {
		Program program = null;
		try {
		
			program = new Program();
			program.run();
		
		}catch(IOException ie) {

			ie.printStackTrace();
			System.err.println("Exception in Program Constructor..");
		}
		
	}
}
